theme: jekyll-theme-minimal
title: Timestamp - Logbook notes
description: Homepage of an iOS app for creating time focuses notes
github:
  is_project_page: false
  is_user_page: false
  show_downloads: false
